variable "tenancy_ocid" {}
variable "region" {}
variable "compartment_ocid" {}
variable "ssh_auth_keys" {}
variable "vcn_name" {}
variable "vcn_dns" {}
variable "vcn_cidr" {}
variable "pub_cidr" {}
variable "priv_cidr" {}
variable "provision_cidr" {}
variable "bastion_image" {}
variable "jumphost_image" {}
variable "sddc_cidr" {}
variable "sddc_display_name" {}
variable "sddc_version" {}
variable "sddc_esxi_hosts_count" {}
variable "sddc_is_hcx_enabled" {}
variable "sddc_workload_network_cidr" {}
variable "sddc_instance_display_name_prefix" {}
variable "sddc_repl_cidr" {}
variable "sddc_nsxEdgeUplink1_cidr" {}
variable "sddc_nsxEdgeUplink2_cidr" {}
variable "sddc_vSAN_cidr" {}
variable "sddc_vMotion_cidr" {}
variable "sddc_provision_cidr" {}
variable "sddc_HCX_cidr" {}
variable "sddc_NSX-VTEP_cidr" {}
variable "sddc_vSphere_cidr" {}
variable "sddc_NSX-Edge-VTEP_cidr" {}